# Server Port Config
server.port=${PORT:8081}
server.servlet.context-path=

# Spring Data MongoDB Configuration (MongoDB Atlas Cloud Cluster)
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://User:Mnbvcxz123%40%23@cluster0.4osn4zj.mongodb.net/yognasetu_db?retryWrites=true&w=majority}

# Security & JWT Configuration
yognasetu.jwt.secret=${JWT_SECRET:YognaSetuSecureSuperSecretKeyForSpringSecurityAuthenticationTokenSigning2026!}
yognasetu.jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}

# API Documentation Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true

# Logging Level
logging.level.org.springframework.security=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
